### ISSUE TITLE
Integrate MiMa

### ISSUE THREAD

**Issue by chuwy** [snowplow/iglu-scala-client#97] opened 2018-07-18 14:39 UTC
https://github.com/lightbend/migration-manager

FGE JSON Schema and Jackson databind as well as few other ancient dependencies are most common source of runtime failures in our code base. MiMa should make upgrades a lot easier.

**Comment by istreeter** [comment] 2021-07-02 16:08
Duplicate of #118 which is merged

**Closed by istreeter** 2021-07-02 16:08 UTC
